export const lightTheme = {
  color_background: "#F0F0F7",
  color_primary_lighter: "#9871F5",
  color_primary_light: "#916BEA",
  color_primary: "#8257E5",
  color_primary_dark: "#774DD6",
  color_primary_darker: "#6842C2",
  color_secondary: "#04D361",
  color_secondary_dark: "#04BF58",
  color_title_in_primary: "#FFFFFF",
  color_text_in_primary: "#D4C2FF",
  color_text_title: "#32264D",
  color_text_complement: "#9C98A6",
  color_text_base: "#6A6180",
  color_line_in_white: "#E6E6F0",
  color_input_background: "#F8F8FC",
  color_button_text: "#FFFFFF",
  color_box_base: "#FFFFFF",
  color_box_footer: "#FAFAFC",
};

export const darkTheme = {
  color_background: "#121212",
  color_primary_lighter: "#9871F5",
  color_primary_light: "#916BEA",
  color_primary: "#8257E5",
  color_primary_dark: "#774DD6",
  color_primary_darker: "#6842C2",
  color_secondary: "#288b54",
  color_secondary_dark: "#04BF58",
  color_title_in_primary: "#FFFFFF",
  color_text_in_primary: "#afacb6",
  color_text_title: "#dfdffa",
  color_text_complement: "#9C98A6",
  color_text_base: "#e9e2f9",
  color_line_in_white: "hsl(0deg 3% 21%)",
  color_input_background: "hsl(0deg 0% 33%)",
  color_button_text: "#FFFFFF",
  color_box_base: "#2e2e2e",
  color_box_footer: "#3c3c3c",
};

export type themeTypes = typeof lightTheme;
